Добавлена возможность очищать линии
Vasilii-Khusamov/WinFormsApp_Test2 pull request #5
Opened 2022-08-15 13:32 UTC by Vasilii-Khusamov

2022-08-16 08:45 UTC, khusamov requested changes

2022-08-16 08:45 UTC, khusamov commented on Program.cs
> +				new ClearLinesRule(),
Переименовать правило. Сейчас оно звучит 'Правило четких линий'

2022-08-16 08:45 UTC, khusamov commented on Utils/BrickMapOperations.cs
> +		public static Brush[,] ClearLines(Brush[,] target, bool[] rows)
Добавить описание метода ClearLines()

2022-08-16 08:45 UTC, khusamov commented on Utils/BrickMapOperations.cs
> +			for (int row1 = 0; row1 <= rows.GetUpperBound(0); row1++)
row1 <= rows.GetUpperBound(0) заменить на row1 < rows.Length

2022-08-16 08:45 UTC, khusamov commented on Utils/BrickMapOperations.cs
> +				if (row1 > result.GetUpperBound(0)) break;
Эту проверку удалить, так как количество элементов rows всегда равно количеству строк target. Возможно поставить проверку количества элементов rows вначале метода.

2022-08-16 08:45 UTC, khusamov commented on Utils/BrickMapOperations.cs
> +						for (int col = 0; col <= result.GetUpperBound(1); col++)
Воспользоваться GetSize из расширения

2022-08-16 08:45 UTC, khusamov commented on Rules/ClearLinesRule.cs
> +            for (int row = 0; row <= gameState.Cup.GetUpperBound(0); row++)
Опять забыли GetSize

2022-08-16 08:45 UTC, khusamov commented on Rules/ClearLinesRule.cs
> +            if (tempScore == 4) tempScore = 1000;
Добавить переменную rowsClearedNumber (количество очищенный строк), чтобы вместо строки 42 написать if (rowsClearedNumber == 4) tempScore = 1000;

2022-08-20 14:59 UTC, Vasilii-Khusamov commented on Utils/BrickMapOperations.cs
> +				if (row1 > result.GetUpperBound(0)) break;
Зачем?

2022-08-20 15:21 UTC, Vasilii-Khusamov commented on Utils/BrickMapOperations.cs
> +				if (row1 > result.GetUpperBound(0)) break;
Это не улучшит работу метода

2022-08-20 15:41 UTC, Vasilii-Khusamov commented on Utils/BrickMapOperations.cs
> +				if (row1 > result.GetUpperBound(0)) break;
Окей

2022-08-20 15:55 UTC, khusamov approved these changes

2022-08-20 15:57 UTC, merged